title: Soki's Blog
author: lszero
email: intzero@outlook.com
description: > 
  程序媛/小硕/外协/折腾/技术宅
url: http://lszero.com 
baseurl: "" 

# Markdown Processors
markdown: kramdown

plugins:
  - jekyll-paginate
paginate: 5
paginate_path: "/pages:num/"

mathjax: false

excerpt_separator: <!-- more -->

permalink: /:categories/:title.html

social_media:
  github_url: https://github.com/lszero
  weibo_url: http://weibo.com/u/2313016370
  zhihu_url: https://www.zhihu.com/people/lszero
  twitter_url: https://twitter.com/_lszero
  lofter_url: http://intzero.lofter.com/
